### ISSUE TITLE
can this addon be renamed?

### ISSUE THREAD

**Issue by ofZach** [borg/ofxSVG#3]
there is a core addon called ofxSvg so this is conflicting (even through it's ofxSvg vs ofxSVG).  maybe a rename is helpful, otherwise this addon can only be used in non standard folders.

**Comment by borg** [comment]
I'd say that's a good idea. Even I get confused these days. This was started way back before there was a core addon.
Having said that, having the ability to modify, merge and export (also on iOS) would be great features to add to the core one. I haven't compared features lately, but maybe porting key functionality would be a good idea as well? Just a thought, I don't know how much work that would be.

**Comment by borg** [comment]
https://github.com/borg/ofxEditableSVG te gusta?
